apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
        - image: httpd:latest
          name: httpd
          resources: {}
status: {}

---
kubectl set image deployment/web-app httpd=httpd:bookworm -n staging
