apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: dev3
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.40-bookworm
      nodeSelector:
        role: backend