apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  

  clusterIP: None

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-service-ingress  
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-service
            port:
              number: 80