kubectl label nodes node01 dataProcessing=true
kubectl label nodes controlplane webServer=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-processing
  name: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-processing
    spec:
      containers:
        - image: redis
          name: redis
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: DoesNotExist
                topologyKey: webServer
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-server
    spec:
      containers:
        - image: httpd
          name: httpd
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: DoesNotExist
                topologyKey: dataProcessing
status: {}
